### ISSUE TITLE
gimp@2.10.18-2: decompress error

### ISSUE THREAD

**Issue by liuhaowen478** [lukesampson/scoop-extras#3911] opened 2020-04-22 02:35 UTC
```
Extracting gimp-2.10.18-setup-2.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\liuha\scoop\apps\gimp\2.10.18-2\gimp-2.10.18-setup-2.exe.
Log file:
  ~\scoop\apps\gimp\2.10.18-2\innounp.log
```
[innounp.log](https://github.com/lukesampson/scoop-extras/files/4513496/innounp.log)

**Comment by Ash258** [comment] 2020-04-22 05:16
Duplicate of #3804

**Closed by Ash258** 2020-04-22 05:16 UTC
