### ISSUE TITLE
gimp@2.10.18-2: decompress error

### ISSUE THREAD

**Issue by sdaaish** [lukesampson/scoop-extras#3805] opened 2020-04-02 17:51 UTC
scoop install -f gimp
Installing 'gimp' (2.10.18-2) [64bit]
Loading gimp-2.10.18-setup-2.exe from cache
Checking hash of gimp-2.10.18-setup-2.exe ... ok.
Extracting gimp-2.10.18-setup-2.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\sdaa\scoop\apps\gimp\2.10.18-2\gimp-2.10.18-setup-2.exe.
Log file:
  ~\scoop\apps\gimp\2.10.18-2\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=gimp%402.10.18-2%3a+decompress+error

**Comment by Ash258** [comment] 2020-04-02 17:52
Duplicate of #3804

**Closed by Ash258** 2020-04-02 17:52 UTC
