### ISSUE TITLE
[Request] Update brave to Release v1.25.69

### ISSUE THREAD

**Issue by fingahoverit** [lukesampson/scoop-extras#6299] opened 2021-06-03 08:25 UTC
https://github.com/brave/brave-browser/releases/tag/v1.25.69 

Any recommandation or disapproval about brave? 
Scoop updates are are off since a long time.

**Comment by Ash258** [comment] 2021-06-03 08:26
Duplicate of #5954

**Closed by Ash258** 2021-06-03 08:26 UTC
