### ISSUE TITLE
Throttlestop 9.4.2 url invalid

### ISSUE THREAD

**Issue by udit** [lukesampson/scoop-extras#6877] opened 2021-09-19 13:00 UTC
Throttlestop 9.4.2 update is not working.

```
Updating 'throttlestop' (9.4 -> 9.4.2)
Downloading new version
The remote server returned an error: (404) Not Found.
At D:\Program Files\Scoop\apps\scoop\current\lib\install.ps1:130 char:9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : The remote server returned an error: (404) Not Found.
```

**Comment by Ash258** [comment] 2021-09-19 13:01
Duplicate of #6756

**Closed by Ash258** 2021-09-19 13:01 UTC
