### ISSUE TITLE
neovim 0.3.5 (currently 0.3.4 in scoop)

### ISSUE THREAD

**Issue by habamax** [lukesampson/scoop-extras#2158] opened 2019-05-17 06:57 UTC
Hi, 

Could you add neovim 0.3.5, please?

https://github.com/neovim/neovim/releases/tag/stable

Thx!

**Comment by Ash258** [comment] 2019-05-17 07:00
ScoopInstaller/Main#32, neovim/neovim#10011

Duplicate of lukesampson/scoop#3464

**Comment by niheaven** [comment] 2019-05-25 15:55
Should be closed now. https://github.com/neovim/neovim/issues/10011#issuecomment-495918446

**Comment by xarthurx** [comment] 2019-05-25 16:29
Not yet.
see https://github.com/ScoopInstaller/Main/pull/32.
hash check failed.

**Comment by r15ch13** [comment] 2019-05-26 09:58
Fixed with https://github.com/ScoopInstaller/Main/pull/88

**Closed by r15ch13** 2019-05-26 09:58 UTC
