### ISSUE TITLE
Can't shim 'pandoc.exe'

### ISSUE THREAD

**Issue by habamax** [lukesampson/scoop-extras#3607] opened 2020-02-16 20:06 UTC
I have tried to update pandoc and got an error:

![image](https://user-images.githubusercontent.com/234774/74611856-e1edb500-5110-11ea-8859-90eeeeaee9ef.png)

Uninstall&Reinstall didn't help.

**Comment by Ash258** [comment] 2020-02-16 20:09
Duplicate of ScoopInstaller/Main#812

**Closed** 2020-02-16 20:09 UTC
