### ISSUE TITLE
CudaText

### ISSUE THREAD

**Issue by slaughtering** [lukesampson/scoop-extras#4393] opened 2020-07-08 07:21 UTC
Please use links like below:
https://www.fosshub.com/CudaText.html?dwl=cudatext-win-x64-1.106.6.1.zip
Links like https://www.fosshub.com/CudaText.html/cudatext-win-x64-1.106.0.1.zip don't seem to work.

**Comment by Ash258** [comment] 2020-07-08 07:23
Duplicate of #4152 (lukesampson/scoop#4051)

**Closed by Ash258** 2020-07-08 07:23 UTC
