### ISSUE TITLE
gimp@2.10.18-2: decompress error

### ISSUE THREAD

**Issue by fiammanda** [lukesampson/scoop-extras#3904] opened 2020-04-20 14:13 UTC
Error (Exception) "MoveFile failed; code 225.%nOperation did not complete successfully because the file contains a virus or potentially unwanted software" at address 0048BFFC

**Comment by Ash258** [comment] 2020-04-20 14:52
Duplicate of #3804

**Closed by Ash258** 2020-04-20 14:52 UTC
Labels: duplicate
