### ISSUE TITLE
gimp@2.10.18-2: decompress error

### ISSUE THREAD

**Issue by carlosrabelo** [lukesampson/scoop-extras#3835] opened 2020-04-10 18:50 UTC
When trying to install Gimp, the following message appears:

Failed to extract files from C: \ Users \ ... \ scoop \ apps \ gimp \ 2.10.18-2 \ gimp-2.10.18-setup-2.exe.
Log file:
   ~ \ scoop \ apps \ gimp \ 2.10.18-2 \ innounp.log

**Comment by Ash258** [comment] 2020-04-17 18:44
Duplicate of #3804

**Closed by Ash258** 2020-04-17 18:44 UTC
Labels: duplicate
