### ISSUE TITLE
Running "code" from Win+R opens extra Console terminal window

### ISSUE THREAD

**Issue by gavenkoa** [lukesampson/scoop-extras#4715] opened 2020-09-06 13:38 UTC
VSCode starts via `C:\opt\scoop\shims\code.cmd`. As it is a batch file it opens console if there is no attached console.

It is annoying to have open Console.

All methods, like https://www.raymond.cc/blog/hidden-start-runs-batch-files-silently-without-flickering-console/ are cumbersome. I don't know what is the efficient way to open GUI app without console.

**Comment by Ash258** [comment] 2020-09-06 13:41
Duplicate of lukesampson/scoop#3634

**Closed by Ash258** 2020-09-06 13:41 UTC
