### ISSUE TITLE
winscp@5.15.4: hash check failed

### ISSUE THREAD

**Issue by Chillax89** [lukesampson/scoop-extras#2950] opened 2019-10-09 07:49 UTC
Hi Admin,

I tried using scoop in install WinSCP to my machine but the harsh does not meet the actual harsh. Please refer below for the error message encountered:

App:         extras/winscp
URL:         https://downloads.sourceforge.net/project/winscp/WinSCP/5.15.4/WinSCP-5.15.4-Portable.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    317eff4325718b51c0fabcd514539af2d1d6db8b8d458a2cc8a724d57d615bd8
Actual:      56d45410cb8c7926d511ad56089530325fdd828bb930375d5acde70edc699b13

Thanks for the help.

Cheers.

**Comment by linsui** [comment] 2019-10-09 07:57
Can't reproduce, please try again.

**Comment by Jogai** [comment] 2019-10-23 19:21
fixed by 5.15.5

**Closed** 2019-10-26 20:25 UTC
