### ISSUE TITLE
freeclipboardviewer@3.0: hash check failed

### ISSUE THREAD

**Issue by mano1404** [lukesampson/scoop-extras#4464] opened 2020-07-26 21:27 UTC
Installing 'freeclipboardviewer' (3.0) [64bit]

FreeClipViewer.zip (22 B) [===================================================================================] 100%
Checking hash of FreeClipViewer.zip ... ERROR Hash check failed!
App:         extras/freeclipboardviewer
URL:         http://www.freeclipboardviewer.com/FreeClipViewer.zip
First bytes: 50 4B 05 06 00 00 00 00
Expected:    2e56d300c131f082275eadac01aaa535216fdfa965eedf2c64dfc63eff5bbfeb
Actual:      8739c76e681f900923b900c9df0ef75cf421d39cabb54650c4b9ad19b6a76d85

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=freeclipboardviewer%403.0%3a+hash+check+failed

**Comment by Ash258** [comment] 2020-07-26 21:27
Duplicate of #4432

**Closed by Ash258** 2020-07-26 21:27 UTC
Labels: hash-fix-needed, verified
