### ISSUE TITLE
gpu-z@2.41.0: download failed

### ISSUE THREAD

**Issue by FDUZS** [lukesampson/scoop-extras#6700] opened 2021-08-25 15:36 UTC
```
Updating 'gpu-z' (2.40.0 -> 2.41.0)
Downloading new version
The remote server returned an error: (404) Not Found.
At D:\Scoop\apps\scoop\current\lib\install.ps1:130 char:9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : The remote server returned an error: (404) Not Found.
```

the download URL changed again. seems like some random characters and timestamp added to it.

**Comment by FDUZS** [comment] 2021-09-04 01:35
I tried with `scoop config aria2-user-agent winget`, `scoop config aria2-user-agent winget/1.0` and `scoop config aria2-user-agent "winget/1.0"` to set up the user agent, while all failed. I doubt there may not exist such an option in Scoop.

fine, `scoop uninstall gpu-z -p`, use winget instead.

Reference:

https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-U
https://scoop-docs.vercel.app/docs/misc/Multi-connection-downloads-with-aria2.html

**Comment by Ash258** [comment] 2021-09-10 17:40
Duplicate of #6754

**Closed by Ash258** 2021-09-10 17:40 UTC
Labels: package-fix-needed, help-wanted, verified
