### ISSUE TITLE
sysinternals@February.18.2019: hash check failed

### ISSUE THREAD

**Issue by waynearthurtondidata** [lukesampson/scoop-extras#1819] opened 2019-03-06 19:42 UTC
Checking hash of SysinternalsSuite.zip ... ERROR Hash check failed!
App:         extras/sysinternals
URL:         https://download.sysinternals.com/files/SysinternalsSuite.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    a510c31c2cc591a16f342e7cba5dc8409eaf08c9b56729cf132c95c69e196787
Actual:      9b9d6bd0718a5680b2322398345271142783156dc8d6f3642bce72f80337850f

**Comment by antonburger** [comment] 2019-03-06 23:42
Duplicate of #1809.

**Comment by rasa** [comment] 2019-03-07 03:19
Fixed in https://github.com/lukesampson/scoop-extras/commit/e6789d1c27ec4ac1be1298981acb3d5c3e92137d

**Closed by rasa** 2019-03-07 03:19 UTC
