### ISSUE TITLE
[Issue] cannot update to firefox-developer@71.0b10 from 71.0b9

### ISSUE THREAD

**Issue by LoZeno** [lukesampson/scoop-extras#3204] opened 2019-11-18 09:26 UTC
I guess this still depends on firefox-developer "unorthodox" version number;
having firefox-developer version 71.0b9 installed, I can't `scoop update firefox-developer` to get version 71.0b10, I get the message:
`firefox-developer: 71.0b9 (latest version)`
but the manifest shows that version 71.0b10 is available

**Comment by Ash258** [comment] 2019-11-18 09:29
`scoop update firefox-developer -f`

Duplicate of lukesampson/scoop#2720

**Closed by Ash258** 2019-11-18 09:29 UTC
