### ISSUE TITLE
Update PowerToys

### ISSUE THREAD

**Issue by Sei-lus** [lukesampson/scoop-extras#6281] opened 2021-05-30 18:53 UTC
PowerToys is at version 0.22 on the repo. Current version is at 0.37.2.
https://github.com/lukesampson/scoop-extras/blob/master/bucket/powertoys.json
https://github.com/microsoft/PowerToys/releases

**Comment by Ash258** [comment] 2021-05-30 19:12
Duplicate of #5084

**Closed by Ash258** 2021-05-30 19:12 UTC

**Comment by Sei-lus** [comment] 2021-06-01 13:24
I'm sorry for the duplicate. Was going to try and make the update myself, thanks for linking me to the other issue. Will look harder next time.
