### ISSUE TITLE
Chrome Error  0x80004005

### ISSUE THREAD

**Issue by aj0413** [lukesampson/scoop-extras#3672] opened 2020-03-09 02:40 UTC
Just wanted to inquire about this error reported when Chrome tries to check it's own version. Not rightly sure what causes this behavior but wanted to open a ticket to ask.

**Comment by mark05e** [comment] 2020-03-10 12:41
There is not enough context for this. Could you provide steps to reproduce the issue and maybe some screenshots? I think might not be related to scoop.

**Comment by issaclin32** [comment] 2020-03-22 09:35
I got the same problem. It is possibly because the **seperate Google update package** is missing. The update package will be installed if you use the installer, but will not be installed if you use *Scoop*.

You can just update Chrome by `scoop update chrome`.

See https://portableapps.com/node/52443

**Comment by aj0413** [comment] 2020-03-22 22:54
> There is not enough context for this. Could you provide steps to reproduce the issue and maybe some screenshots? I think might not be related to scoop.

Sorry about the late responsel got caught up in work and totally forgot to check back.

> I got the same problem. It's possibly because the **seperate Google update package** is missing. The update package will be installed if you use the installer, but will not be installed if you use _Scoop_.
> 
> You can just update Chrome by `scoop update googlechrome`
> 
> See https://portableapps.com/node/52443

I had assumed it was something to on chrome's side; thanks for the verification. Been too lazy to dig into it since, yeah, the maintaners are pretty good about versioninging updates here withe googlechrome manifest

**Closed** 2020-03-22 22:55 UTC
