### ISSUE TITLE
msiafterburner@4.6.0: extract_dir error

### ISSUE THREAD

**Issue by lambdanerd** [lukesampson/scoop-extras#1316] opened 2018-10-12 19:58 UTC
```pwsh
~ $ scoop install msiafterburner
Installing 'msiafterburner' (4.6.0) [64bit]
Loading MSIAfterburnerSetup.zip from cache
Checking hash of MSIAfterburnerSetup.zip ... ok.
Extracting MSIAfterburnerSetup460.7z ... DEBUG
-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows                             
-------------------------------------------------------------------------------

  Started : Friday, October 12, 2018 2:53:12 PM
   Source : C:\Users\gouda\scoop\apps\msiafterburner\4.6.0\_tmp\4.6.0\
     Dest : C:\Users\gouda\scoop\apps\msiafterburner\4.6.0\

    Files : *.*

  Options : *.* /S /E /DCOPY:DA /COPY:DAT /MOVE /R:1000000 /W:30

------------------------------------------------------------------------------

2018/10/12 14:53:12 ERROR 2 (0x00000002) Accessing Source Directory C:\Users\gouda\scoop\apps\msiafterburner\4.6.0\_tmp\4.6.0\
The system cannot find the file specified.

ERROR Could not find '4.6.0'! (error 16)
```

**Comment by Gargauth** [comment] 2018-10-14 16:33
It was caused by release of beta version, it should be fixed when https://github.com/lukesampson/scoop-extras/pull/1318 is merged.

**Comment by r15ch13** [comment] 2018-10-15 11:39
#1318 has been merged

**Closed by r15ch13** 2018-10-15 11:39 UTC
