### ISSUE TITLE
gimp@2.10.18-2: decompress error

### ISSUE THREAD

**Issue by DigitalFunk** [lukesampson/scoop-extras#4075] opened 2020-05-16 19:55 UTC
Unable to install GIMP, see console output:

C:\Users\jfunk>scoop install gimp
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'gimp' (2.10.18-2) [64bit]
Starting download with aria2 ...
Download: [#93e8bb 0B/0B CN:1 DL:0B]
Download: [#93e8bb 0B/0B CN:1 DL:0B]
Download: [#93e8bb 288KiB/171MiB(0%) CN:5 DL:461KiB ETA:6m19s]
Download: [#93e8bb 1.1MiB/171MiB(0%) CN:5 DL:738KiB ETA:3m56s]
Download: [#93e8bb 2.7MiB/171MiB(1%) CN:5 DL:1.0MiB ETA:2m43s]
Download: [#93e8bb 5.2MiB/171MiB(3%) CN:5 DL:1.4MiB ETA:1m55s]
Download: [#93e8bb 8.9MiB/171MiB(5%) CN:5 DL:1.9MiB ETA:1m23s]
Download: [#93e8bb 16MiB/171MiB(9%) CN:5 DL:3.0MiB ETA:51s]
Download: [#93e8bb 26MiB/171MiB(15%) CN:5 DL:4.0MiB ETA:35s]
Download: [#93e8bb 35MiB/171MiB(20%) CN:5 DL:4.6MiB ETA:29s]
Download: [#93e8bb 41MiB/171MiB(24%) CN:5 DL:4.8MiB ETA:26s]
Download: [#93e8bb 49MiB/171MiB(29%) CN:5 DL:5.1MiB ETA:23s]
Download: [#93e8bb 59MiB/171MiB(34%) CN:5 DL:6.1MiB ETA:17s]
Download: [#93e8bb 67MiB/171MiB(39%) CN:5 DL:6.8MiB ETA:15s]
Download: [#93e8bb 72MiB/171MiB(42%) CN:5 DL:7.2MiB ETA:13s]
Download: [#93e8bb 84MiB/171MiB(49%) CN:5 DL:8.0MiB ETA:10s]
Download: [#93e8bb 87MiB/171MiB(50%) CN:5 DL:7.9MiB ETA:10s]
Download: [#93e8bb 91MiB/171MiB(53%) CN:5 DL:7.4MiB ETA:10s]
Download: [#93e8bb 100MiB/171MiB(58%) CN:5 DL:7.1MiB ETA:9s]
Download: [#93e8bb 108MiB/171MiB(63%) CN:5 DL:7.3MiB ETA:8s]
Download: [#93e8bb 113MiB/171MiB(66%) CN:5 DL:6.9MiB ETA:8s]
Download: [#93e8bb 120MiB/171MiB(70%) CN:5 DL:6.8MiB ETA:7s]
Download: [#93e8bb 125MiB/171MiB(73%) CN:5 DL:6.6MiB ETA:6s]
Download: [#93e8bb 131MiB/171MiB(76%) CN:5 DL:6.3MiB ETA:6s]
Download: [#93e8bb 139MiB/171MiB(81%) CN:5 DL:6.3MiB ETA:5s]
Download: [#93e8bb 144MiB/171MiB(84%) CN:5 DL:6.0MiB ETA:4s]
Download: [#93e8bb 149MiB/171MiB(87%) CN:4 DL:6.3MiB ETA:3s]
Download: [#93e8bb 149MiB/171MiB(87%) CN:4 DL:5.6MiB ETA:3s]
Download: [#93e8bb 150MiB/171MiB(87%) CN:4 DL:4.9MiB ETA:4s]
Download: [#93e8bb 150MiB/171MiB(88%) CN:4 DL:4.2MiB ETA:4s]
Download: [#93e8bb 151MiB/171MiB(88%) CN:4 DL:3.6MiB ETA:5s]
Download: [#93e8bb 152MiB/171MiB(89%) CN:4 DL:3.1MiB ETA:5s]
Download: [#93e8bb 154MiB/171MiB(90%) CN:4 DL:2.4MiB ETA:6s]
Download: [#93e8bb 156MiB/171MiB(91%) CN:4 DL:2.0MiB ETA:7s]
Download: [#93e8bb 159MiB/171MiB(93%) CN:4 DL:1.7MiB ETA:6s]
Download: [#93e8bb 161MiB/171MiB(94%) CN:3 DL:1.3MiB ETA:7s]
Download: [#93e8bb 165MiB/171MiB(96%) CN:4 DL:1.6MiB ETA:3s]
Download: [#93e8bb 167MiB/171MiB(97%) CN:3 DL:1.7MiB ETA:2s]
Download: [#93e8bb 169MiB/171MiB(98%) CN:2 DL:1.9MiB ETA:1s]
Download: [#93e8bb 170MiB/171MiB(99%) CN:1 DL:1.9MiB]
Download: [#93e8bb 171MiB/171MiB(99%) CN:1 DL:1.9MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 93e8bb|OK  |   4.3MiB/s|C:/Users/jfunk/scoop/cache/gimp#2.10.18-2#https_download.gimp.org_mirror_pub_gimp_v2.10_windows_gimp-2.10.18-setup-2.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of gimp-2.10.18-setup-2.exe ... ok.
Extracting gimp-2.10.18-setup-2.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\jfunk\scoop\apps\gimp\2.10.18-2\gimp-2.10.18-setup-2.exe.
Log file:
  ~\scoop\apps\gimp\2.10.18-2\innounp.log

[innounp.log](https://github.com/lukesampson/scoop-extras/files/4639142/innounp.log)

**Comment by Ash258** [comment] 2020-05-16 20:06
Duplicate of #3804

**Closed by Ash258** 2020-05-16 20:06 UTC
