### ISSUE TITLE
bulk-rename-utility@3.4.1.0: hash check failed

### ISSUE THREAD

**Issue by mikepruett3** [lukesampson/scoop-extras#4809] opened 2020-09-24 02:42 UTC
Checking hash of BRU_setup.exe ... ERROR Hash check failed!
App:         extras/bulk-rename-utility
URL:         https://www.bulkrenameutility.co.uk/Downloads/BRU_setup.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    248f6c1396f8f0cfd2227f08ce229991
Actual:      9c76ff88ad96682e4289c29f491758e7

**Comment by craigktreasure** [comment] 2020-09-24 18:48
This is a duplicate of #4799.

**Closed** 2020-09-25 01:32 UTC
