### ISSUE TITLE
gimp@2.10.18-2: decompress error; windows defender block installation

### ISSUE THREAD

**Issue by ProximaB** [lukesampson/scoop-extras#3873] opened 2020-04-17 10:57 UTC
<details>
  <summary>Windows defender</summary>  

 [<img width=400 src="https://user-images.githubusercontent.com/15923605/79561062-f6b2de80-80a8-11ea-944e-318690d1d0f1.png"/>](https://user-images.githubusercontent.com/15923605/79561062-f6b2de80-80a8-11ea-944e-318690d1d0f1.png)

</details>

<details>
<summary>Powershell output</summary>

```bash
PS C:\WINDOWS\system32> scoop install gimp
Updating Scoop...
Updating 'extras' bucket...
 * 884d2d59 vscode: Update to version 1.44.2                             2 hours ago
 * c78d07d0 vscode-portable: Update to version 1.44.2                    2 hours ago
 * 897a194c sweethome3d: Update to version 6.3                           2 hours ago
 * 2c190386 zeebe-modeler: Update to version 0.9.0                       4 hours ago
 * f2246022 winfbe: Update to version 2.1.2                              4 hours ago
 * 50c2eb52 v2rayn: Update to version 3.15.2                             4 hours ago
 * bc6e81de universal-ctags: Update to version 2020-04-17                4 hours ago
 * 3526012e multrin: Update to version 1.3.0                             4 hours ago
 * 632fe7be mockoon: Update to version 1.8.0                             4 hours ago
 * 876ba2be mailspring: Update to version 1.7.5                          4 hours ago
 * 2bf44dac etcher: Update to version 1.5.81                             4 hours ago
 * 67059b2e chromium: Update to version 81.0.4044.113                    4 hours ago
Updating 'main' bucket...
 * afb373ee ffmpeg-nightly: Update to version 20200417-889ad93           28 minutes ago
 * 7f861f4d broot: Update to version 0.13.6 (#989)                       2 hours ago
 * 6355c6ac gitkube: Disable checkver (#988)                             2 hours ago
 * 65973716 wavpack: Update to version 5.3.0                             3 hours ago
 * 4dbdb055 vim-nightly: Update to version 8.2.0587                      3 hours ago
 * 4e36364f terraform-provider-ibm: Update to version 1.4.0              3 hours ago
 * 7a2eb5f3 pshazz: Update to version 0.2020.04.16                       3 hours ago
 * 02bcae7e n-m3u8dl-cli: Update to version 2.6.1                        3 hours ago
 * 1719950f minio-client: Update to version 2020-04-17T02-56-18Z         3 hours ago
 * 231f6dd0 jx: Update to version 2.0.1285                               3 hours ago
 * 6ffcb1de helmfile: Update to version 0.109.1                          3 hours ago
 * c6f415b8 grex: Update to version 1.1.0                                3 hours ago
 * 5be055a3 geoipupdate: Update to version 4.3.0                         3 hours ago
 * 669dc543 flow: Update to version 0.123.0                              3 hours ago
 * 82c4ce5b fd: Update to version 8.0.0                                  3 hours ago
 * c61f598d deno: Update to version 0.41.0                               3 hours ago
Scoop was updated successfully!
Installing 'innounp' (0.49) [64bit]
innounp049.rar (137,6 KB) [===================================================================================] 100%
Checking hash of innounp049.rar ... ok.
Extracting innounp049.rar ... done.
Linking ~\scoop\apps\innounp\current => ~\scoop\apps\innounp\0.49
Creating shim for 'innounp'.
'innounp' (0.49) was installed successfully!
Installing 'gimp' (2.10.18-2) [64bit]
gimp-2.10.18-setup-2.exe (171,3 MB) [=========================================================================] 100%
Checking hash of gimp-2.10.18-setup-2.exe ... ok.
Extracting gimp-2.10.18-setup-2.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\barte\scoop\apps\gimp\2.10.18-2\gimp-2.10.18-setup-2.exe.
Log file:
  ~\scoop\apps\gimp\2.10.18-2\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=gimp%402.10.18-2%3a+decompress+error
```
</details>

<details>
<summary>Content inside ~\scoop\apps\gimp\2.10.18-2\innounp.log</summary>

```bash
#15111 {app}\lib\gimp\2.0\plug-ins\file-psp\file-psp,2.exe
#15112 {app}\lib\gimp\2.0\plug-ins\file-raw-data\file-raw-data,2.exe
#15113 {app}\lib\gimp\2.0\plug-ins\file-raw-placeholder\file-raw-placeholder,2.exe
#15114 {app}\lib\gimp\2.0\plug-ins\file-rawtherapee\file-rawtherapee,2.exe
#15115 {app}\lib\gimp\2.0\plug-ins\file-sgi\file-sgi,2.exe
#15116 {app}\lib\gimp\2.0\plug-ins\file-sunras\file-sunras,2.exe
#15117 {app}\lib\gimp\2.0\plug-ins\file-svg\file-svg,2.exe
#15118 {app}\lib\gimp\2.0\plug-ins\file-tga\file-tga,2.exe
#15119 {app}\lib\gimp\2.0\plug-ins\file-tiff\file-tiff,2.exe
#15120 {app}\lib\gimp\2.0\plug-ins\file-webp\file-webp,2.exe
#15121 {app}\lib\gimp\2.0\plug-ins\file-wmf\file-wmf,2.exe
#15122 {app}\lib\gimp\2.0\plug-ins\file-xbm\file-xbm,2.exe
#15123 {app}\lib\gimp\2.0\plug-ins\file-xpm\file-xpm,2.exe
#15124 {app}\lib\gimp\2.0\plug-ins\file-xwd\file-xwd,2.exe
#15125 {app}\lib\gimp\2.0\plug-ins\film\film,2.exe
#15126 {app}\lib\gimp\2.0\plug-ins\filter-pack\filter-pack,2.exe
#15127 {app}\lib\gimp\2.0\plug-ins\flame\flame,2.exe
#15128 {app}\lib\gimp\2.0\plug-ins\fractal-explorer\fractal-explorer,2.exe
#15129 {app}\lib\gimp\2.0\plug-ins\fractal-trace\fractal-trace,2.exe
#15130 {app}\lib\gimp\2.0\plug-ins\gfig\gfig,2.exe
#15131 {app}\lib\gimp\2.0\plug-ins\gimpressionist\gimpressionist,2.exe
#15132 {app}\lib\gimp\2.0\plug-ins\goat-exercise\goat-exercise,2.exe
#15133 {app}\lib\gimp\2.0\plug-ins\gradient-flare\gradient-flare,2.exe
#15134 {app}\lib\gimp\2.0\plug-ins\gradient-map\gradient-map,2.exe
#15135 {app}\lib\gimp\2.0\plug-ins\grid\grid,2.exe
#15136 {app}\lib\gimp\2.0\plug-ins\guillotine\guillotine,2.exe
#15137 {app}\lib\gimp\2.0\plug-ins\help\help,2.exe
#15138 {app}\lib\gimp\2.0\plug-ins\help-browser\help-browser,2.exe
#15139 {app}\lib\gimp\2.0\plug-ins\hot\hot,2.exe
#15140 {app}\lib\gimp\2.0\plug-ins\ifs-compose\ifs-compose,2.exe
#15141 {app}\lib\gimp\2.0\plug-ins\imagemap\imagemap,2.exe
#15142 {app}\lib\gimp\2.0\plug-ins\jigsaw\jigsaw,2.exe
#15143 {app}\lib\gimp\2.0\plug-ins\lighting\lighting,2.exe
#15144 {app}\lib\gimp\2.0\plug-ins\map-object\map-object,2.exe
#15145 {app}\lib\gimp\2.0\plug-ins\max-rgb\max-rgb,2.exe
#15146 {app}\lib\gimp\2.0\plug-ins\metadata-editor\metadata-editor,2.exe
#15147 {app}\lib\gimp\2.0\plug-ins\metadata-viewer\metadata-viewer,2.exe
#15148 {app}\lib\gimp\2.0\plug-ins\nl-filter\nl-filter,2.exe
#15149 {app}\lib\gimp\2.0\plug-ins\pagecurl\pagecurl,2.exe
#15150 {app}\lib\gimp\2.0\plug-ins\photocopy\photocopy,2.exe
#15151 {app}\lib\gimp\2.0\plug-ins\plugin-browser\plugin-browser,2.exe
#15152 {app}\lib\gimp\2.0\plug-ins\print\print,2.exe
#15153 {app}\lib\gimp\2.0\plug-ins\procedure-browser\procedure-browser,2.exe
#15154 {app}\lib\gimp\2.0\plug-ins\qbist\qbist,2.exe
#15155 {app}\lib\gimp\2.0\plug-ins\sample-colorize\sample-colorize,2.exe
#15156 {app}\lib\gimp\2.0\plug-ins\screenshot\screenshot,2.exe
#15157 {app}\lib\gimp\2.0\plug-ins\script-fu\script-fu,2.exe
#15158 {app}\lib\gimp\2.0\plug-ins\selection-to-path\selection-to-path,2.exe
#15159 {app}\lib\gimp\2.0\plug-ins\sharpen\sharpen,2.exe
#15160 {app}\lib\gimp\2.0\plug-ins\smooth-palette\smooth-palette,2.exe
#15161 {app}\lib\gimp\2.0\plug-ins\softglow\softglow,2.exe
#15162 {app}\lib\gimp\2.0\plug-ins\sparkle\sparkle,2.exe
#15163 {app}\lib\gimp\2.0\plug-ins\sphere-designer\sphere-designer,2.exe
#15164 {app}\lib\gimp\2.0\plug-ins\tile\tile,2.exe
#15165 {app}\lib\gimp\2.0\plug-ins\tile-small\tile-small,2.exe
#15166 {app}\lib\gimp\2.0\plug-ins\unit-editor\unit-editor,2.exe
#15167 {app}\lib\gimp\2.0\plug-ins\van-gogh-lic\van-gogh-lic,2.exe
#15168 {app}\lib\gimp\2.0\plug-ins\warp\warp,2.exe
#15169 {app}\lib\gimp\2.0\plug-ins\wavelet-decompose\wavelet-decompose,2.exe
#15170 {app}\lib\gimp\2.0\plug-ins\web-browser\web-browser,2.exe
#15171 {app}\lib\gimp\2.0\plug-ins\web-page\web-page,2.exe
#15172 {app}\bin\.debug\gimp-2.10.exe,2.debug
#15173 {app}\bin\.debug\gimp-console-2.10.exe,2.debug
#15174 {app}\bin\.debug\gimp-console.exe,2.debug
#15175 {app}\bin\.debug\gimp-debug-resume.exe,2.debug
#15176 {app}\bin\.debug\gimp-debug-tool-2.0.exe,2.debug
#15177 {app}\bin\.debug\gimp-test-clipboard-2.0.exe,2.debug
#15178 {app}\bin\.debug\gimp.exe,2.debug
#15179 {app}\bin\.debug\gimptool-2.0.exe,2.debug
#15180 {app}\bin\.debug\libgimp-2.0-0.dll,2.debug
#15181 {app}\bin\.debug\libgimpbase-2.0-0.dll,2.debug
#15182 {app}\bin\.debug\libgimpcolor-2.0-0.dll,2.debug
#15183 {app}\bin\.debug\libgimpconfig-2.0-0.dll,2.debug
#15184 {app}\bin\.debug\libgimpmath-2.0-0.dll,2.debug
#15185 {app}\bin\.debug\libgimpmodule-2.0-0.dll,2.debug
#15186 {app}\bin\.debug\libgimpthumb-2.0-0.dll,2.debug
#15187 {app}\bin\.debug\libgimpui-2.0-0.dll,2.debug
#15188 {app}\bin\.debug\libgimpwidgets-2.0-0.dll,2.debug
#15189 {app}\lib\gimp\2.0\modules\.debug\libcolor-selector-cmyk.dll,2.debug
#15190 {app}\lib\gimp\2.0\modules\.debug\libcolor-selector-water.dll,2.debug
#15191 {app}\lib\gimp\2.0\modules\.debug\libcolor-selector-wheel.dll,2.debug
#15192 {app}\lib\gimp\2.0\modules\.debug\libcontroller-dx-dinput.dll,2.debug
#15193 {app}\lib\gimp\2.0\modules\.debug\libdisplay-filter-clip-warning.dll,2.debug
#15194 {app}\lib\gimp\2.0\modules\.debug\libdisplay-filter-color-blind.dll,2.debug
#15195 {app}\lib\gimp\2.0\modules\.debug\libdisplay-filter-gamma.dll,2.debug
#15196 {app}\lib\gimp\2.0\modules\.debug\libdisplay-filter-high-contrast.dll,2.debug
#15197 {app}\lib\gimp\2.0\plug-ins\align-layers\.debug\align-layers.exe,2.debug
#15198 {app}\lib\gimp\2.0\plug-ins\animation-optimize\.debug\animation-optimize.exe,2.debug
#15199 {app}\lib\gimp\2.0\plug-ins\animation-play\.debug\animation-play.exe,2.debug
#15200 {app}\lib\gimp\2.0\plug-ins\blinds\.debug\blinds.exe,2.debug
#15201 {app}\lib\gimp\2.0\plug-ins\blur\.debug\blur.exe,2.debug
#15202 {app}\lib\gimp\2.0\plug-ins\border-average\.debug\border-average.exe,2.debug
#15203 {app}\lib\gimp\2.0\plug-ins\busy-dialog\.debug\busy-dialog.exe,2.debug
#15204 {app}\lib\gimp\2.0\plug-ins\cartoon\.debug\cartoon.exe,2.debug
#15205 {app}\lib\gimp\2.0\plug-ins\checkerboard\.debug\checkerboard.exe,2.debug
#15206 {app}\lib\gimp\2.0\plug-ins\cml-explorer\.debug\cml-explorer.exe,2.debug
#15207 {app}\lib\gimp\2.0\plug-ins\color-cube-analyze\.debug\color-cube-analyze.exe,2.debug
#15208 {app}\lib\gimp\2.0\plug-ins\color-enhance\.debug\color-enhance.exe,2.debug
Error (Exception) "MoveFile failed; code 225.%nOperation did not complete successfully because the file contains a virus or potentially unwanted software" at address 0048BFFC
```
</details>

# Workaround
### Go to `C:\Users\{user}\scoop\cache`, locate the installation file and execute it manually.

**Comment by Ash258** [comment] 2020-04-17 18:44
Duplicate of #3804

**Closed by Ash258** 2020-04-17 18:44 UTC
Labels: duplicate
