### ISSUE TITLE
typora@0.11.5: decompress error

### ISSUE THREAD

**Issue by thbenedicto** [lukesampson/scoop-extras#6666] opened 2021-08-20 11:46 UTC
```
c:\>scoop install typora
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'typora' (0.11.5) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 7b0078|OK  |    10MiB/s|E:/apps-scoop/cache/typora#0.11.5#https_typora.io_windows_typora-setup-x64.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of typora-setup-x64.exe ... ok.
Extracting typora-setup-x64.exe ... Invoke-ExternalCommand : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At E:\apps-scoop\apps\scoop\current\lib\decompress.ps1:192 char:38
+ ... tus = Invoke-ExternalCommand (Get-HelperPath -Helper Innounp) $ArgLis ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from E:\apps-scoop\apps\typora\0.11.5\typora-setup-x64.exe.
Log file:
  E:\apps-scoop\apps\typora\0.11.5\innounp.log
```

**Comment by Ash258** [comment] 2021-08-20 11:49
Duplicate of lukesampson/scoop#3517

**Closed by Ash258** 2021-08-20 11:49 UTC
