### ISSUE TITLE
Jaspersoft-studio has errors uninstalling

### ISSUE THREAD

**Issue by tomihawk** [lukesampson/scoop-extras#2389] opened 2019-06-30 15:18 UTC
The following install/uninstall demonstrates that uninstall has issues removing files.  It leaves the persisted data behind and looks like the issue is with the space in the filename.

```
D:\Products>scoop install jaspersoft-studio
Installing 'jaspersoft-studio' (6.9.0) [64bit]
Loading TIB_js-studiocomm_6.9.0_windows_x86_64.zip from cache
Checking hash of TIB_js-studiocomm_6.9.0_windows_x86_64.zip ... ok.
Extracting TIB_js-studiocomm_6.9.0_windows_x86_64.zip ... done.
Linking ~\scoop\apps\jaspersoft-studio\current => ~\scoop\apps\jaspersoft-studio\6.9.0
Creating shortcut for Jaspersoft Studio (Jaspersoft Studio.exe)
Persisting configuration
Persisting Jaspersoft Studio.ini
'jaspersoft-studio' (6.9.0) was installed successfully!

D:\Products>scoop uninstall jaspersoft-studio
Uninstalling 'jaspersoft-studio' (6.9.0).
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Jaspersoft Studio.lnk
Unlinking ~\scoop\apps\jaspersoft-studio\current
Could Not Find C:\Users\ThomasLocal\scoop\apps\jaspersoft-studio\6.9.0\Jaspersoft
Could Not Find D:\Products\Studio.ini
'jaspersoft-studio' was uninstalled.

D:\Products>
```

**Comment by Ash258** [comment] 2019-06-30 18:21
Duplicate of lukesampson/scoop#2801

**Closed** 2019-10-18 12:04 UTC
