### ISSUE TITLE
Notepad3 not on latest release

### ISSUE THREAD

**Issue by mark05e** [lukesampson/scoop-extras#5614] opened 2021-02-03 18:24 UTC
As per https://github.com/rizonesoft/Notepad3/releases, the current release is 5.20.915.1 (September 2020) 

while https://github.com/lukesampson/scoop-extras/blob/master/bucket/notepad3.json runs on 5.20.722.1

**Comment by Ash258** [comment] 2021-02-07 08:56
Duplicate of #2308

**Closed by Ash258** 2021-02-07 08:56 UTC
