### ISSUE TITLE
bulk-crap-uninstaller@4.12.3: Crash on start

### ISSUE THREAD

**Issue by JanPokorny** [lukesampson/scoop-extras#1746] opened 2019-02-18 20:30 UTC
When installing BCUninstaller through scoop, the installation runs with no problem, but the installed BCUninstaller crashes soon after starting it (after requesting admin privilegies) with `System.UnauthorizedAccessException`, stating that access to `C:\Users\JP\scoop\apps\bulk-crap-uninstaller\current\BCUninstaller.settings` was denied. Happens on both local and global install (always showing the current path to `BCUninstaller.settings`).

**Comment by JanPokorny** [comment] 2019-02-18 20:31
Ping @Paratsu who made the original manifest

**Comment by rikuben** [comment] 2019-02-18 23:13
Duplicate of #1682 ?
Adding this script should fix it I think.
```
"pre_install": [
    "if (!(Test-Path(\"$dir/BCUninstaller.settings\"))) {",
    "   New-Item \"$dir/BCUninstaller.settings\" | Out-Null",
    "}"
],
```

**Closed** 2019-02-19 20:56 UTC
