### ISSUE TITLE
firefox-beta update is not detected

### ISSUE THREAD

**Issue by dinNew** [lukesampson/scoop-extras#3229] opened 2019-11-21 06:45 UTC
ran `scoop update` saw a message about firefox-beta being updated.

`scoop status` doesn't show update.
`scoop update firefox-beta` also says latest version is already installed.

tried it again, didn't detect. same `scoop status` result.
tried it everyday since, update hasn't been detected. same `scoop status` result. current firefox-beta version  **71.0b9** 

----

ran it again after writing the above, doesn't detect.

```
> scoop status                                                                                        Scoop is up to date.
Everything is ok!
```

```
> scoop update firefox-beta                                                                           firefox-beta: 71.0b9 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

also ran this command now, and I'm confused.

```
> scoop info firefox-beta                                                                             Name: firefox-beta
Description: Beta builds of Firefox: the popular open source web browser.
Version: 71.0b9 (Update to 71.0b11 available)
Website: https://www.mozilla.org/en-US/firefox/beta/
License: MPL-2.0 (https://spdx.org/licenses/MPL-2.0.html)
Manifest:
  D:\scoop\buckets\extras\bucket\firefox-beta.json
Installed:
  D:\scoop\apps\firefox-beta\71.0b9
Binaries:
  firefox-beta.exe
```

tried `scoop reset` then 
```
> scoop status                                                                                        Scoop is up to date.
Everything is ok!
```

did not uninstall the app for reasons.

---

thanks dinNew

**Comment by linsui** [comment] 2019-11-21 06:47
Please try `scoop update firefox-beta -f`

**Comment by dinNew** [comment] 2019-11-21 06:48
I thinks its better to **warn users** that scoop's extra bucket is really problematic and not mature yet.
Save them the trouble of wasting their time trying experimental stuff.

---

thanks dinNew

**Comment by dinNew** [comment] 2019-11-21 06:49
trying what you suggested. was already writing above comment before you posted.

---

thanks dinNew

**Comment by dinNew** [comment] 2019-11-21 07:02
its confusing that a option that is described as  `-f, --force               Force update even when there isn't a newer version` by `scoop help` solves this.

thanks for the help. when this gets fixed by https://github.com/lukesampson/scoop/pull/3721, this issue gets closed, I think.
 
---

thanks dinNew

**Comment by Ash258** [comment] 2019-11-21 07:27
Duplicate of lukesampson/scoop#2720

**Closed by Ash258** 2019-11-21 07:27 UTC
