### ISSUE TITLE
sysinternals version number issue

### ISSUE THREAD

**Issue by hkse7en** [lukesampson/scoop-extras#6613] opened 2021-08-11 15:39 UTC
Hi, I found an issue about the sysinternals.
One month ago I installed it (version 2021.June.xx)
Today I found that there was a new version 2021.July.27, but after `scoop update`; `scoop status`, it said all OK no updates.
I ran `scoop update sysinternals -f`, it installed 2021.July.27.
Then I ran `scoop cleanup *`, it removed 2021.July.27 and kept the 2021.June.xx.
As it counted on the alphabet order (so Ju**N**e is newer than Ju**L**y)

**Comment by Ash258** [comment] 2021-08-17 07:00
Duplicate of lukesampson/scoop#2720

**Closed by Ash258** 2021-08-17 07:00 UTC
