### ISSUE TITLE
totalcommander@9.22a: hash check failed

### ISSUE THREAD

**Issue by goostleek** [lukesampson/scoop-extras#1955] opened 2019-04-01 11:31 UTC
```bash
$ scoop install totalcommander
Installing 'totalcommander' (9.22a) [64bit]
tcmd922ax64.exe (4,9 MB) [===========================================================================================================================] 100%
Checking hash of tcmd922ax64.exe ... ERROR Hash check failed!
App:         extras/totalcommander
URL:         http://totalcommander.ch/win/tcmd922ax64.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    8f5e7ca9303382b7617bd509d1a3897cb7009c4c4b1d9e46b21e81a9cf065ac3
Actual:      9a01bcdd67d99e31cbe6512161829c86fddb25496d6d98b4f140923ad856af1f
```

**Comment by f0ff886f** [comment] 2019-04-02 10:48
Dupe of #1950

**Comment by r15ch13** [comment] 2019-04-03 16:29
Fixed with https://github.com/lukesampson/scoop-extras/pull/1952

**Closed by r15ch13** 2019-04-03 16:29 UTC
