### ISSUE TITLE
Failed updates getting flagged as installed

### ISSUE THREAD

**Issue by Stanzilla** [lukesampson/scoop-extras#1720] opened 2019-02-10 16:52 UTC
Not sure if this is something for the main repo or related to the extras bucket but I guess you guys can move it if it is. When I tried to install ccleaner (https://github.com/lukesampson/scoop-extras/issues/1710) and enpass (https://github.com/lukesampson/scoop-extras/issues/1711) and it failed they both were flagged as installed and I had to uninstall them before I could install them again.

**Comment by Ash258** [comment] 2019-02-10 16:56
Duplicate of lukesampson/scoop#3089

see: https://github.com/lukesampson/scoop/issues/3089#issuecomment-461075464

**Comment by Stanzilla** [comment] 2019-02-10 17:17
@Ash258 ah, closed, which is why I did not find them. That should be reopened then?

**Comment by JanPokorny** [comment] 2019-02-18 20:52
@Ash258 Is there an open issue tracking this? (On the main repo, I suppose?) This issue is very annoying, as it can leave apps in an inconsistent state. It makes much more sense to first download the file to cache, and then start the installation/update process.

**Closed** 2019-02-19 17:36 UTC
