### ISSUE TITLE
[Request] Add JabRef

### ISSUE THREAD

**Issue by uyfv554** [lukesampson/scoop-extras#3935] opened 2020-04-25 22:35 UTC
JabRef is an open source bibliography reference manager written in Java. JabRef is a good tool for managing your reference when you write academic papers or prepare course projects.

[homepage](https://www.jabref.org/)

**Comment by Ash258** [comment] 2020-04-25 22:37
Duplicate of #3164

**Comment by Ash258** [comment] 2020-04-25 22:37
Why did you opened it again as soon as the first one was closed as duplicate??

**Closed by Ash258** 2020-04-25 22:37 UTC
Labels: duplicate
