### ISSUE TITLE
NMAP 7.9.0 - Silent Install only supported in OEM

### ISSUE THREAD

**Issue by everonline** [lukesampson/scoop-extras#4862] opened 2020-10-04 12:04 UTC
Hi team,

It seems the update from 7.8.0 to 7.9.0 in nmap went rogue:

`Installing 'nmap' (7.90) [64bit]
Loading nmap-7.90-setup.exe from cache
Checking hash of nmap-7.90-setup.exe ... ok.
Running installer... error.
ERROR Exit code was 2!
Installation aborted. You might need to run 'scoop uninstall nmap' before trying again.`

Silent Install only supported in OEM.

**Comment by Ash258** [comment] 2020-10-04 13:08
Duplicate of ScoopInstaller/Main#1465

**Closed by Ash258** 2020-10-04 13:08 UTC
