### ISSUE TITLE
[Request] Add git-extras

### ISSUE THREAD

**Issue by 7wells** [lukesampson/scoop-extras#4714] opened 2020-09-06 09:51 UTC
Hello,

Would you mind adding this? https://github.com/tj/git-extras
It has, for example, [git force-clone](https://github.com/tj/git-extras/blob/master/Commands.md#git-force-clone), which I find useful in certain circumstances.

Thank you so much for your kind consideration.

**Comment by Ash258** [comment] 2020-10-28 16:14
Duplicate of #4947

**Closed by Ash258** 2020-10-28 16:14 UTC
Labels: help-wanted, request
