### ISSUE TITLE
An incomplete solution for updating Microsoft PowerToys

### ISSUE THREAD

**Issue by g-berthiaume** [lukesampson/scoop-extras#5138] opened 2020-11-17 15:29 UTC
I was trying to do my first scoop PR, but I encountered a problem.   
So I'm flagging this issue with my incomplete solution.

**Context**  
As of today, [PowerToys](https://github.com/microsoft/PowerToys/) is stuck to v0.21, because Microsoft has stopped distributing `.msi` in their releases. This file was required for `autoupdate` to run. 
Now, the [documentation](https://github.com/microsoft/PowerToys/wiki/Installer-arguments-for-exe) suggests passing flags to their `.exe` instead.

Here's what my updated powertoys.json looks like
```json
{
    "version": "0.25.0",
    "description": "A set of utilities for power users to tune and streamline their Windows experience for greater productivity.",
    "homepage": "https://github.com/microsoft/PowerToys",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/microsoft/PowerToys/releases/download/v0.25.0/PowerToysSetup-0.25.0-x64.exe",
            "hash": "E857C78D68FF628E624D470871DEA6197D9E58D74A183DAF6418309812C3C91F",
            "installer": {
            	"args": "--silent"
            }
        }
    },
    "extract_dir": "PowerToys",
    "shortcuts": [
        [
            "PowerToys.exe",
            "PowerToys"
        ]
    ],
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/microsoft/PowerToys/releases/download/v$version/PowerToysSetup-$version-x64.exe"
            }
        }
    }
}
``` 
I have updated the `URL` to use the `.exe` and added an `installer` args.
The `--silent` flag should run the installer without any GUI.

**Problem**   
When running this new `json`, scoop will not install PowerToys locally.
I'm not sure how scoop maintainers normally handles this kind of problem. 

Could you take a look at it? I'm looking forward to learning about how to solve this problem.

n.b.
Also, there's a [bug](https://github.com/microsoft/PowerToys/issues/7332) that prevents the program to start automatically.

**Comment by g-berthiaume** [comment] 2020-11-17 15:33
Hum I just read https://github.com/lukesampson/scoop-extras/issues/5084
Maybe the problem cannot be fixed without modifying PowerToys itself.

**Comment by Ash258** [comment] 2020-11-17 15:35
Duplicate of #5084

**Closed by Ash258** 2020-11-17 15:35 UTC
