### ISSUE TITLE
gpu-z@2.42.0: Download failed

### ISSUE THREAD

**Issue by valentinpi** [lukesampson/scoop-extras#6900] opened 2021-09-24 20:23 UTC
The link gives a 404.
```
PS C:\Users\User> scoop update gpu-z
gpu-z: 2.41.0 -> 2.42.0
Updating one outdated app:
Updating 'gpu-z' (2.41.0 -> 2.42.0)
Downloading new version
OperationStopped: C:\Users\Valentin\scoop\apps\scoop\current\lib\install.ps1:130
Line |
 130 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.
```

**Comment by Ash258** [comment] 2021-09-25 08:18
Duplicate of #6754

**Closed by Ash258** 2021-09-25 08:18 UTC
Labels: package-fix-needed, help-wanted, verified
