### ISSUE TITLE
terminal: Add Windows Terminal Preview v0.7.3291.0

### ISSUE THREAD

**Issue by shytikov** [lukesampson/scoop-extras#3314] opened 2019-12-05 21:05 UTC
Add new Windows Terminal: https://github.com/microsoft/terminal/

**Comment by Ash258** [comment] 2019-12-05 21:06
Duplicate of #2921 

Being added in #3054

**Closed by Ash258** 2019-12-05 21:06 UTC

**Comment by shytikov** [comment] 2019-12-06 09:40
@Ash258 on #3054 process had stuck a while ago. So I took all code from there, fixed all suggestions, updated to most recent version and submitted new PR.
