### ISSUE TITLE
Free Download Manager installation error

### ISSUE THREAD

**Issue by wh7** [lukesampson/scoop-extras#2218] opened 2019-05-30 06:27 UTC
```
The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command
 name, a script block, or a CommandInfo object.
At line:1 char:3
+ & (Get-HelperPath 'innounp') -x -d"$dir" "$dir\$fname" -y | Out-Null
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression
 
Move-Item : Cannot find path 'C:\Users\lain\scoop\apps\freedownloadmanager\5.1.38\{app}' because it does not exis
t.
At line:2 char:1
+ Move-Item "$dir\{app}\*" "$dir" | Out-Null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\lain\s...er\5.1.38\{app}:String) [Move-Item], ItemNotFou 
   ndException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand
 
Move-Item : Cannot find path 'C:\Users\lain\scoop\apps\freedownloadmanager\5.1.38\{code_CefInstallDir}' because i
t does not exist.
At line:3 char:1
+ Move-Item "$dir\{code_CefInstallDir}\*" "$dir" | Out-Null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\lain\s..._CefInstallDir}:String) [Move-Item], ItemNotFou 
   ndException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand
 
Remove-Item : Cannot find path 'C:\Users\lain\scoop\apps\freedownloadmanager\5.1.38\install_script.iss' because i
t does not exist.
At line:5 char:5
+     Remove-Item "$dir\$_" -Recurse -Force
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\lain\s...tall_script.iss:String) [Remove-Item], ItemNotF 
   oundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
Remove-Item : Cannot find path 'C:\Users\lain\scoop\apps\freedownloadmanager\5.1.38\{app}' because it does not ex
ist.
At line:5 char:5
+     Remove-Item "$dir\$_" -Recurse -Force
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\lain\s...er\5.1.38\{app}:String) [Remove-Item], ItemNotF 
   oundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
Remove-Item : Cannot find path 'C:\Users\lain\scoop\apps\freedownloadmanager\5.1.38\{code_CefInstallDir}' because
 it does not exist.
At line:5 char:5
+     Remove-Item "$dir\$_" -Recurse -Force
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\lain\s..._CefInstallDir}:String) [Remove-Item], ItemNotF 
   oundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
Linking ~\scoop\apps\freedownloadmanager\current => ~\scoop\apps\freedownloadmanager\5.1.38
Creating shortcut for Free Download Manager (fdm.exe) failed: Couldn't find C:\Users\lain\scoop\apps\freedownloadmanager\current\fdm.exe
```

**Comment by Ash258** [comment] 2019-05-30 06:32
Duplicate of #2150

**Closed** 2019-06-04 15:14 UTC
