### ISSUE TITLE
mc@4.8.21: download via aria2 failed

### ISSUE THREAD

**Issue by bsneisen** [lukesampson/scoop-extras#1891] opened 2019-03-21 13:18 UTC
ERROR Download failed! (Error 3) Resource was not found
ERROR https://downloads.sourceforge.net/project/mcwin32/mcwin32-build209-bin.zip
    dir=C:\Users\bsnei\scoop\cache
    out=mc#4.8.21#https_downloads.sourceforge.net_project_mcwin32_mcwin32-build209-bin.zip

ERROR & 'C:\Users\bsnei\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\bsnei\scoop\cache\mc.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=15376 --continue

**Comment by r15ch13** [comment] 2019-03-21 17:35
Duplicate of https://github.com/lukesampson/scoop-extras/issues/1891

**Closed by r15ch13** 2019-03-21 17:35 UTC
