### ISSUE TITLE
gimp@2.10.18-2: decompress error

### ISSUE THREAD

**Issue by junliangxing** [lukesampson/scoop-extras#3871] opened 2020-04-17 06:09 UTC
![image](https://user-images.githubusercontent.com/3126767/79537523-ff111680-80b4-11ea-8ba6-47e9c16da300.png)

D:\GreenSoft\System\Scoop\apps\gimp\2.10.18-2\innounp.log
......
#15199 {app}\lib\gimp\2.0\plug-ins\animation-play\.debug\animation-play.exe,2.debug
#15200 {app}\lib\gimp\2.0\plug-ins\blinds\.debug\blinds.exe,2.debug
#15201 {app}\lib\gimp\2.0\plug-ins\blur\.debug\blur.exe,2.debug
#15202 {app}\lib\gimp\2.0\plug-ins\border-average\.debug\border-average.exe,2.debug
#15203 {app}\lib\gimp\2.0\plug-ins\busy-dialog\.debug\busy-dialog.exe,2.debug
#15204 {app}\lib\gimp\2.0\plug-ins\cartoon\.debug\cartoon.exe,2.debug
#15205 {app}\lib\gimp\2.0\plug-ins\checkerboard\.debug\checkerboard.exe,2.debug
#15206 {app}\lib\gimp\2.0\plug-ins\cml-explorer\.debug\cml-explorer.exe,2.debug
#15207 {app}\lib\gimp\2.0\plug-ins\color-cube-analyze\.debug\color-cube-analyze.exe,2.debug
#15208 {app}\lib\gimp\2.0\plug-ins\color-enhance\.debug\color-enhance.exe,2.debug
Error (Exception) "MoveFile failed; code 225.%n??????????????????????????" at address 0048BFFC

**Comment by Ash258** [comment] 2020-04-17 18:44
Duplicate of #3804

**Closed by Ash258** 2020-04-17 18:44 UTC
Labels: duplicate
