### ISSUE TITLE
Cannot start chromium

### ISSUE THREAD

**Issue by eheintzmann** [lukesampson/scoop-extras#2779] opened 2019-08-31 14:52 UTC
After installing chromium 76.0.3809.100-r665002 (`scoop intall chromium`), the commands `chrome.exe` and  `chromium.exe` do not work (on _cmd_ or _powershell_, they do nothing, but with _git bash_ there is a segmentation fault).
And double clicking on the chromium icon (in Scoop Apps), do nothing too

**Comment by linsui** [comment] 2019-09-01 02:46
I can't reproduce it. Please try `scoop reset chromium` or reinstall it.

**Comment by eheintzmann** [comment] 2019-09-01 08:09
I've tried `scoop reset chromium` and reinstall it.
It still does not work

**Comment by eheintzmann** [comment] 2019-09-01 08:45
I've tried to run chrome with windbg:
there is an Access violation - code c0000005

**Comment by issaclin32** [comment] 2019-09-01 15:36
I cannot reproduce the problem either.

It might be related with plugins or extensions.
You can try running `chromium --disable-extensions --disable-plugins` and see if it solves the problem.

**Comment by eheintzmann** [comment] 2019-09-03 09:54
No changes with `chromium --disable-extensions --disable-plugins`

**Comment by eheintzmann** [comment] 2019-09-13 23:03
You are right:
64bit doesn't work but 32bit version works fine.

**Comment by tratTalks** [comment] 2019-11-17 16:51
close this now?
---

cheers tratTalks

**Closed** 2019-11-18 14:48 UTC
