### ISSUE TITLE
brackets@1.14.2: decompress error

### ISSUE THREAD

**Issue by Surf3r2** [lukesampson/scoop-extras#4780] opened 2020-09-18 07:22 UTC
Error 1304. Error writing to file: C:\Users\User\scoop\apps\brackets\1.14.2\_tmp\SourceDir\Brackets\www\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan\package.json. Verify that you have access to that directory.

**Comment by Ash258** [comment] 2020-09-18 07:24
Duplicate of #4326

**Closed by Ash258** 2020-09-18 07:24 UTC
