### ISSUE TITLE
musescore@3.0.4.5763: download via aria2 failed

### ISSUE THREAD

**Issue by panathos** [lukesampson/scoop-extras#1793] opened 2019-03-02 12:56 UTC
ERROR Download failed! (Error 3) Resource was not found
ERROR https://ftp.osuosl.org/pub/musescore/releases/MuseScore-3.0.4/MuseScore-3.0.4.msi
    referer=https://ftp.osuosl.org/pub/musescore/releases/MuseScore-3.0.4/
    dir=D:\Scoop\cache
    out=musescore#3.0.4.5763#https_ftp.osuosl.org_pub_musescore_releases_MuseScore-3.0.4_MuseScore-3.0.4.msi

ERROR & 'D:\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Scoop\cache\musescore.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=9468 --continue

**Comment by shoogle** [comment] 2019-03-03 18:00
Probably a duplicate of #1788, which has now been fixed by #1789. Please update scoop and try again.

**Closed** 2019-03-03 18:14 UTC
