### ISSUE TITLE
[Request] Add VeraCrypt

### ISSUE THREAD

**Issue by devhawk** [lukesampson/scoop-extras#5659] opened 2021-02-10 18:32 UTC
I'd open a PR, but I'm not sure how to build the right manifest for VeraCrypt. https://www.veracrypt.fr/en/Downloads.html includes a "Portable" version for windows, but the portable version is distributed as a self-extracting exe (more details: https://www.veracrypt.fr/code/VeraCrypt/plain/doc/html/Portable%20Mode.html)

**Comment by Ash258** [comment] 2021-02-10 18:33
Duplicate of #2381

**Closed by Ash258** 2021-02-10 18:33 UTC
