### ISSUE TITLE
cudatext@1.111.6.0: download via aria2 failed

### ISSUE THREAD

**Issue by marciliocn** [lukesampson/scoop-extras#4743] opened 2020-09-12 07:54 UTC
When I try install Cudatext, I got this message:
```
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'cudatext' (1.111.6.0) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 09712b|ERR |        n/a|C:/Users/t480s/scoop/cache/cudatext#1.111.6.0#https_www.fosshub.com_CudaText.html_cudatext-win-x64-1.111.6.0.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR 
    referer=https://www.fosshub.com/CudaText.html/
    dir=C:\Users\t480s\scoop\cache
    out=cudatext#1.111.6.0#https_www.fosshub.com_CudaText.html_cudatext-win-x64-1.111.6.0.zip

ERROR & 'C:\Users\t480s\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\t480s\scoop\cache\cudatext.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=1996 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=cudatext%401.111.6.0%3a+download+via+aria2+failed
```

**Comment by Ash258** [comment] 2020-09-12 07:55
lukesampson/scoop#4051

Duplicate of #4152

**Closed by Ash258** 2020-09-12 07:55 UTC
Labels: help-wanted, package-fix-needed, verified
