### ISSUE TITLE
furmark@1.23.0.0: decompress error

### ISSUE THREAD

**Issue by leni8ec** [lukesampson/scoop-extras#5218] opened 2020-11-30 19:38 UTC
Checking hash of FurMark_1.23.0.0_Setup.exe ... ok.
Extracting FurMark_1.23.0.0_Setup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Scoop\apps\furmark\1.23.0.0\FurMark_1.23.0.0_Setup.exe.
Log file:
  C:\Scoop\apps\furmark\1.23.0.0\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=furmark%401.23.0.0%3a+decompress+error

**Comment by earnestma** [comment] 2020-11-30 21:14
Same thing here. Log file mentioned (@leni8ec, might want to post yours too if it's different):

```
bat ~/scoop/apps/furmark/1.23.0.0/innounp.log
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: C:/Users/earne/scoop/apps/furmark/1.23.0.0/innounp.log
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ Signature detected: Inno Setup Setup Data (6.1.0) (u)
   2   │ This is not directly supported, but i'll try to unpack it as version 6000
   3   │ ; Version detected: 6100 (Unicode)
   4   │ Unpacking failed. This version is not supported.
```

**Comment by earnestma** [comment] 2020-11-30 21:16
Actually this is a duplicate of # 5213 (https://github.com/lukesampson/scoop-extras/issues/5213)

**Closed** 2020-11-30 22:25 UTC
