### ISSUE TITLE
gpu-z@2.42.0: Download via aria2 failed

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [lukesampson/scoop-extras#6904] opened 2021-09-25 19:33 UTC
Download failed!

ERROR & 'C:\Scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Scoop\cache\gpu-z.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=4 --split=16 --max-connection-per-server=16 --min-split-size=4M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=11652 --continue --summary-interval 0
ERROR Download failed! (Error 3) Resource was not found

**Comment by Ash258** [comment] 2021-09-25 19:34
Duplicate of #6754

**Closed by Ash258** 2021-09-25 19:34 UTC
Labels: package-fix-needed, help-wanted, verified
