### ISSUE TITLE
cudatext@1.106.6.1: hash check failed

### ISSUE THREAD

**Issue by zb5213** [lukesampson/scoop-extras#4391] opened 2020-07-08 01:15 UTC
Updating 'cudatext' (1.106.5.0 -> 1.106.6.1)
Downloading new version
Loading cudatext-win-x64-1.106.6.1.zip from cache.
Checking hash of cudatext-win-x64-1.106.6.1.zip ... ERROR Hash check failed!
App:         extras/cudatext
URL:         https://www.fosshub.com/CudaText.html/cudatext-win-x64-1.106.6.1.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    9b0ddf09172b1fa582c2dd4e4a512f4d62f9a182ba98bf7692e95fa0d8b2d0b4
Actual:      bb588e71e1a1773913eb0cb133acecae2496f2f513abec2aeebf92cd44a26ba0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=cudatext%401.106.6.1%3a+hash+check+failed

**Comment by Ash258** [comment] 2020-07-08 05:07
Duplicate of #4152 (lukesampson/scoop#4051)

**Closed by Ash258** 2020-07-08 05:07 UTC
