### ISSUE TITLE
gpu-z@2.41.0: download via aria2 failed

### ISSUE THREAD

**Issue by lcnsf18** [lukesampson/scoop-extras#6754] opened 2021-09-01 01:23 UTC
scoop install gpu-z
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'gpu-z' (2.41.0) [64bit]
Starting download with aria2 ...
Download: 09/01 09:21:36 [ERROR] CUID#8 - Download aborted. URI=http://us2-dl.techpowerup.com/files/GPU-Z.2.41.0.exe#/GPDownload: Download Results:                                                                                   .exe
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: dafda5|ERR |       0B/s|D:/Scoop/cache/gpu-z#2.41.0#http_us2-dl.techpowerup.com_files_GPU-Z.2.41.0.exe_GPU-Z.exe
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR http://us2-dl.techpowerup.com/files/GPU-Z.2.41.0.exe#/GPU-Z.exe
    referer=http://us2-dl.techpowerup.com/files/GPU-Z.2.41.0.exe#/
    dir=D:\Scoop\cache
    out=gpu-z#2.41.0#http_us2-dl.techpowerup.com_files_GPU-Z.2.41.0.exe_GPU-Z.exe

ERROR & 'D:\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Scoop\cache\gpu-z.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=16 --max-connection-per-server=16 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=7924 --continue --summary-interval 0 --all-proxy='127.0.0.1:10809'

Please try again or create a new issue by using the following link and paste your console output:

**Comment by ItzLevvie** [comment] 2021-09-01 10:56
https://github.com/lukesampson/scoop-extras/issues/6700#issuecomment-906515741

**Comment by maver1ck** [comment] 2021-09-16 06:39
Do we have any fix for this ?

**Comment by StarsbySea** [comment] 2021-09-26 05:12
After investigating one side of the techpowerup website, I found that nowadays, to download software (such as GPU-Z) from the website, you must first request the website to get a dynamic download address. The previous direct link download is no longer valid. Here is the verification code to get the GPU-Z download address via Python.
```python
import requests

data = {
    'id': '1995', # unique ID of the software
    'server_id': '3' # The server ID of the requested download
}

response = requests.post('https://www.techpowerup.com/download/techpowerup-gpu-z/', data=data)
print(response.url)
```
This code will output a download link like "https://us2-dl.techpowerup.com/files/0NuHZbMQULDdrQbLHVRqlw/1632675911/GPU-Z.2.42.0.exe", but The two strings of garbled content in the middle seem to have an expiry date and are generated differently each time.
Since I'm not very familiar with PowerShell, there's not much I can do to write a fix.

**Comment by W1zzardTPU** [comment] 2021-09-27 08:35
^Scoop has been added as valid user agent to our servers

```
# curl -I http://us2-dl.techpowerup.com/files/GPU-Z.2.41.0.exe
HTTP/1.1 404 Not Found
Server: nginx/1.20.1
Date: Mon, 27 Sep 2021 08:33:55 GMT
Content-Type: text/html
Content-Length: 153
Connection: keep-alive

# curl -I --user-agent "Scoop/asdf"  http://us2-dl.techpowerup.com/files/GPU-Z.2.41.0.exe                                                    HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Mon, 27 Sep 2021 08:33:47 GMT
Content-Type: application/octet-stream
Content-Length: 7400336
Last-Modified: Fri, 06 Aug 2021 14:05:35 GMT
Connection: keep-alive
ETag: "610d41af-70eb90"
Accept-Ranges: bytes
```

**Comment by maver1ck** [comment] 2021-09-28 06:16
@W1zzardTPU 
I can confirm that your solution is working. Thank you.

**Closed** 2021-09-29 18:24 UTC
Labels: package-fix-needed, help-wanted, verified
