### ISSUE TITLE
brackets@1.14.1: decompress error

### ISSUE THREAD

**Issue by rohancragg** [lukesampson/scoop-extras#3693] opened 2020-03-14 17:50 UTC
```
Installing 'brackets' (1.14.1) [64bit]
Loading Brackets.Release.1.14.1.msi from cache
Checking hash of Brackets.Release.1.14.1.msi ... ok.
Extracting Brackets.Release.1.14.1.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\rohan\scoop\apps\brackets\1.14.1\Brackets.Release.1.14.1.msi.
Log file:
  ~\scoop\apps\brackets\1.14.1\msi.log
```
Log file content:
```
=== Logging started: 14/03/2020  17:47:18 ===
Error 1320. The specified path is too long: C:\Users\rohan\scoop\apps\brackets\1.14.1\_tmp\SourceDir\Brackets\www\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan
=== Logging stopped: 14/03/2020  17:47:41 ===
```

**Comment by Ash258** [comment] 2020-03-14 17:52
Duplicate of #3329

**Closed by Ash258** 2020-03-14 17:52 UTC
